spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: smiledk
    password: 1112
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: trace